node_data = {
            'motor_rpm': None,
            'steer': None,
            'navpvt': None,
            'camera_image': None,
            'gps_fix_velocity': {
                'header': {
                    'seq': None,
                    'stamp_secs': None,
                    'stamp_nsecs': None,
                    'frame_id': None,
                },
                'linear': {
                    'x': None,
                    'y': None,
                    'z': None,
                },
                'angular': {
                    'x': None,
                    'y': None,
                    'z': None,
                },
                'covariance': [],
            },
            'gps_fix': {
                'header': {
                    'seq': None,
                    'stamp_secs': None,
                    'stamp_nsecs': None,
                    'frame_id': None,
                },
                'status': {
                    'status': None,
                    'service': None,
                },
                'latitude': None,
                'longitude': None,
                'altitude': None,
                'position_covariance': [],
                'position_covariance_type': None,
            },
            'zed_depth_camera_info': {
                'header': {
                    'seq': None,
                    'stamp_secs': None,
                    'stamp_nsecs': None,
                    'frame_id': None,
                },
                'height': None,
                'width': None,
                'distortion_model': None,
                'D': [],
                'K': [],
                'R': [],
                'P': [],
                'binning_x': None,
                'binning_y': None,
                'roi': {
                    'x_offset': None,
                    'y_offset': None,
                    'height': None,
                    'width': None,
                    'do_rectify': None,
                },
            },
            'zed_left_camera_info': {
                'header': {
                    'seq': None,
                    'stamp_secs': None,
                    'stamp_nsecs': None,
                    'frame_id': None,
                },
                'height': None,
                'width': None,
                'distortion_model': None,
                'D': [],
                'K': [],
                'R': [],
                'P': [],
                'binning_x': None,
                'binning_y': None,
                'roi': {
                    'x_offset': None,
                    'y_offset': None,
                    'height': None,
                    'width': None,
                    'do_rectify': None,
                },
            },
    }